const menuData = [
  {
    title:'mockApi服务',
    path:null,
    children:[
      {
        title:"项目管理",
        key:"projectsmanage",
        path:"/mockapiservice/projectsmanage",
      },
      {
        title:"Api管理",
        key:"apismanage",
        path:"/mockapiservice/apismanage",
      },
    ]
  },
  {
    title:'other',
    path:null,
    children:[
      {
        title:"item1",
        path:"/other/item1",
        key:"item1",
      }
    ]
  }
];
export default menuData;